### Array types and conversions between types

In [29]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [30]:
integers=np.array([101,202,303,404,505])

In [31]:
integers

array([101, 202, 303, 404, 505])

In [32]:
integers[0]

np.int64(101)

In [33]:
integers[0]=202
integers

array([202, 202, 303, 404, 505])

In [34]:
integers[0]=421.79
integers

array([421, 202, 303, 404, 505])

In [35]:
integers.dtype

dtype('int64')

In [36]:
smallerIntegers=np.array(integers,dtype=np.int8)

In [37]:
smallerIntegers

array([ -91,  -54,   47, -108,   -7], dtype=int8)

In [38]:
integers.nbytes

40

In [39]:
smallerIntegers.nbytes

5

In [40]:
# overflow = np.array([125,126,127,128,129], dtype = np.int8)
# overflow

In [41]:
floats=np.array([1.2,2.3,3.4,4.5])

In [42]:
floats

array([1.2, 2.3, 3.4, 4.5])

In [43]:
floats.dtype

dtype('float64')