### Creating arrays from Lists and more

In [1]:
import numpy as np

In [2]:
first_natural_numbers_list=[1,2,3,4,5,6,7,8,9,10]

In [3]:
first_natural_numbers_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
first_natural_numbers_array=np.array(first_natural_numbers_list)

In [5]:
first_natural_numbers_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
numbers_list=[1,2,4.23,3.2,762.4,89.2,45.2]

In [7]:
numbers_array=np.array(numbers_list)

In [8]:
numbers_array

array([  1.  ,   2.  ,   4.23,   3.2 , 762.4 ,  89.2 ,  45.2 ])

In [9]:
numbers_array.dtype

dtype('float64')

In [10]:
alpha_numeric_list=['Alex',111,'Bob',112,'Catalyna',113,'Dogg',114]


In [11]:
third_array=np.array(alpha_numeric_list)

In [12]:
alpha_numeric_list

['Alex', 111, 'Bob', 112, 'Catalyna', 113, 'Dogg', 114]

In [13]:
numbers_tuple=(5, 10, 15, 20, 25, 30)


In [14]:
numbers_array_from_tuple=np.array(numbers_tuple)

In [15]:
numbers_array_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [16]:
numbers_array_from_tuple.dtype

dtype('int64')

In [17]:
multi_dimensional_list=[[[0,1,2], [3,4,5]], [[6,7,8],[9,10,11]]] 

In [18]:
multi_dimensional_arr=np.array(multi_dimensional_list)

In [19]:
multi_dimensional_arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])