### Intrisic NumPy array creation

In [1]:
import numpy as np

In [2]:
integers_arr1=np.arange(10)
integers_arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
integers_arr2=np.arange(100,200)
integers_arr2

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [4]:
integers_arr3=np.arange(100,201,2)
integers_arr3

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

In [5]:
floats_arr1=np.linspace(10,50)
floats_arr1

array([10.        , 10.81632653, 11.63265306, 12.44897959, 13.26530612,
       14.08163265, 14.89795918, 15.71428571, 16.53061224, 17.34693878,
       18.16326531, 18.97959184, 19.79591837, 20.6122449 , 21.42857143,
       22.24489796, 23.06122449, 23.87755102, 24.69387755, 25.51020408,
       26.32653061, 27.14285714, 27.95918367, 28.7755102 , 29.59183673,
       30.40816327, 31.2244898 , 32.04081633, 32.85714286, 33.67346939,
       34.48979592, 35.30612245, 36.12244898, 36.93877551, 37.75510204,
       38.57142857, 39.3877551 , 40.20408163, 41.02040816, 41.83673469,
       42.65306122, 43.46938776, 44.28571429, 45.10204082, 45.91836735,
       46.73469388, 47.55102041, 48.36734694, 49.18367347, 50.        ])

In [6]:
floats_arr2=np.linspace(10,50,5)
floats_arr2

array([10., 20., 30., 40., 50.])

In [7]:
rand_arr1=np.random.rand(5)
rand_arr1

array([0.40048229, 0.98644274, 0.66081988, 0.90464091, 0.83835112])

In [8]:
rand_arr2=np.random.rand(3,3)
rand_arr2

array([[0.29334784, 0.83171728, 0.76003731],
       [0.0718767 , 0.96101679, 0.78368739],
       [0.27090828, 0.23150169, 0.64778203]])

In [9]:
rand_arr3=np.random.randint(0,49,30)
rand_arr3

array([18, 37,  4, 43,  9,  5,  2, 44, 14, 40, 43, 17, 44, 12, 26, 34,  2,
       36, 37,  6, 44, 28,  6, 11, 31,  0, 18,  5, 16,  0], dtype=int32)