### Creating arrays with constants

In [1]:
import numpy as np

In [2]:
zero_arr1=np.zeros(5)
zero_arr1

array([0., 0., 0., 0., 0.])

In [3]:
zero_arr2=np.zeros((4,5))
zero_arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
ones_arr1=np.ones(6)
ones_arr1

array([1., 1., 1., 1., 1., 1.])

In [5]:
ones_arr2=np.ones((7,8))
ones_arr2

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
ones_arr3=np.ones((4,5),dtype=int)
ones_arr3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
fill_arr1=np.empty(10,dtype=int)
fill_arr1.fill(12)
fill_arr1

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [8]:
full_arr1=np.full(5,10)
full_arr1

array([10, 10, 10, 10, 10])

In [9]:
full_arr2=np.full((4,5),8)
full_arr2

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])