###  Finding the shape and size of an array

In [1]:
import numpy as np

In [2]:
arr1=np.arange(60)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [3]:
arr2=np.linspace((1,2),(10,60),10)
arr2

array([[ 1.        ,  2.        ],
       [ 2.        ,  8.44444444],
       [ 3.        , 14.88888889],
       [ 4.        , 21.33333333],
       [ 5.        , 27.77777778],
       [ 6.        , 34.22222222],
       [ 7.        , 40.66666667],
       [ 8.        , 47.11111111],
       [ 9.        , 53.55555556],
       [10.        , 60.        ]])

In [4]:
arr3=np.full((2,2,2),10)
arr3

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [5]:
np.shape(arr1)

(60,)

In [6]:
np.shape(arr2)

(10, 2)

In [7]:
np.shape(arr3)

(2, 2, 2)

In [8]:
np.size(arr1)

60

In [9]:
np.size(arr2)

20

In [10]:
np.size(arr3)

8