### Adding, removing and sorting elements

In [10]:
import numpy as np

In [11]:
arr1=np.array([1, 2, 4, 5, 6])
arr1

array([1, 2, 4, 5, 6])

In [12]:
arr1_new=np.insert(arr1,1,3)
arr1_new

array([1, 3, 2, 4, 5, 6])

In [13]:
arr2=np.array([1,2,3])
arr2

array([1, 2, 3])

In [14]:
arr2_new=np.append(arr2,4)
arr2_new

array([1, 2, 3, 4])

In [15]:
arr3=np.array([1,2])
arr3

array([1, 2])

In [16]:
arr3_to_delete=np.delete(arr3,1)
arr3_to_delete

array([1])

In [17]:
integers_1d_arr=np.random.randint(0,10,10)
integers_1d_arr

array([8, 8, 7, 0, 3, 7, 6, 5, 1, 0], dtype=int32)

In [18]:
print(np.sort(integers_1d_arr))

[0 0 1 3 5 6 7 7 8 8]


In [19]:
integers_2d_arr=np.array([[-1, -2, 0,7, 2], [4, 9, -2, 8, 9]])
integers_2d_arr

array([[-1, -2,  0,  7,  2],
       [ 4,  9, -2,  8,  9]])

In [20]:
print(np.sort(integers_2d_arr))

[[-2 -1  0  2  7]
 [-2  4  8  9  9]]


In [21]:
colors_arr=np.array(['pink','orange','gray','white','black','yellow','sky blue'])
colors_arr

array(['pink', 'orange', 'gray', 'white', 'black', 'yellow', 'sky blue'],
      dtype='<U8')

In [22]:
print(np.sort(colors_arr))

['black' 'gray' 'orange' 'pink' 'sky blue' 'white' 'yellow']
