### Copies and views

In [1]:
import numpy as np

In [2]:
students_ids_num=np.array([1111,1112,1113,1114,1115,1116,1117,1118])
students_ids_num

array([1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118])

In [3]:
students_ids_num_reg=students_ids_num
print("ID's of students_ids_num",id(students_ids_num))
print("ID's of students_ids_num_reg",id(students_ids_num_reg))

ID's of students_ids_num 2303095467408
ID's of students_ids_num_reg 2303095467408


In [4]:
students_ids_num_reg[1]=1122
print(students_ids_num)
print(students_ids_num_reg)

[1111 1122 1113 1114 1115 1116 1117 1118]
[1111 1122 1113 1114 1115 1116 1117 1118]


In [5]:
students_ids_num_cp=students_ids_num.copy()

In [6]:
print(students_ids_num_cp)

[1111 1122 1113 1114 1115 1116 1117 1118]


In [7]:
print(students_ids_num_cp==students_ids_num)

[ True  True  True  True  True  True  True  True]


In [8]:
print ("ID's of students_ids_num",id(students_ids_num))
print("ID's of students_ids_num_cp",id(students_ids_num_cp))

ID's of students_ids_num 2303095467408
ID's of students_ids_num_cp 2303607238992


In [9]:
students_ids_num[0]=1000
print ("Original ID's: ", students_ids_num)
print("Copy of ID's: ",students_ids_num_cp)

Original ID's:  [1000 1122 1113 1114 1115 1116 1117 1118]
Copy of ID's:  [1111 1122 1113 1114 1115 1116 1117 1118]


In [10]:
students_ids_num_v=students_ids_num.view()

In [11]:
students_ids_num_v[0]=2000
print("Original ID's: ", students_ids_num)
print("Backed (Attached) view of ID's: ",students_ids_num_v)

Original ID's:  [2000 1122 1113 1114 1115 1116 1117 1118]
Backed (Attached) view of ID's:  [2000 1122 1113 1114 1115 1116 1117 1118]


In [12]:
print(students_ids_num_cp.base)
print(students_ids_num_v.base)

None
[2000 1122 1113 1114 1115 1116 1117 1118]
