### Reshaping arrays

In [12]:
import numpy as np

In [13]:
arr1=np.arange(1,17)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [14]:
arr2=np.reshape(arr1,(4,4))
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
arr3=np.reshape(arr1,(8,2))
arr3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [16]:
# arr4=np.reshape(arr1,(3,4))

In [17]:
arr5=np.reshape(arr1,(4,2,2))
print(arr5)
print("Dimensions of fifth_arr is ",arr5.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
Dimensions of fifth_arr is  3


In [18]:
arr6=np.array([[1,2],[3,4],[5,6]])
arr6

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
arr7_to_flatten=np.reshape(arr6,-1)
arr7_to_flatten

array([1, 2, 3, 4, 5, 6])

In [20]:
arr8_to_flatten=arr6.flatten()
print("arr8_to_flatten: ",arr8_to_flatten)
arr9_to_ravel=arr6.ravel()
print("arr9_to_ravel: ",arr9_to_ravel)

arr8_to_flatten:  [1 2 3 4 5 6]
arr9_to_ravel:  [1 2 3 4 5 6]


In [21]:
arr8_to_flatten[0]=10

In [22]:
arr9_to_ravel[0]=20

In [23]:
print("eighth_arr_flat: ",arr8_to_flatten)
print("arr9_to_ravel: ",arr9_to_ravel)
print("arr6: ",arr6)

eighth_arr_flat:  [10  2  3  4  5  6]
arr9_to_ravel:  [20  2  3  4  5  6]
arr6:  [[20  2]
 [ 3  4]
 [ 5  6]]
